---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.9
  - 2.1
  - 2.2
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
    - PUPPET_GEM_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
    - PUPPET_GEM_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
    - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
    - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
matrix:
  fast_finish: true
branches:
  only:
  - spec
notifications:
  email: true
