---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.1.8
env:
  matrix:
    - PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER="yes"
    - PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
matrix:
  fast_finish: true
branches:
  only:
  - spec
notifications:
  email: true
