---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests --full-index
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 2.1.8
  - 2.2.7
  - 2.3.1
  - 2.4.1
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 4" STRICT_VARIABLES=yes
    - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
matrix:
  fast_finish: true
notifications:
  email: false
